site_name: Linked Data Competency Index
pages:
    - Overview: 'index.md'
    - Competency Index: 'D2695955.md'
    - Structure: 'structure.md'
    - Style: 'style.md'
    - Process: 'process.md'
    - Test: 'test.md'
theme: 'readthedocs'
repo_url: https://github.com/dcmi/ldcompindex
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'For crowdsourcing the maintenance and evolution of the LD4PE Linked Data Competency Index'
