site_name: LD4PE Linked Data Competency Index
pages:
    - Overview: 'index.md'
    - CI: 'D2695955.md'
theme: 'readthedocs'
repo_uri: https://github.com/dcmi/ldcompindex
repo_name: 'Github'
edit_url: 'edit/master/docs/'
site_description: 'For crowdsourcing the maintenance and evolution of LD4PE Linked Data Competency Index'
