site_name: Linked Data Competency Index
pages:
    - Overview: 'index.md'
    - The Competency Index: 'D2695955.md'
    - Structure of the Index: 'structure.md'
    - Style of the Index: 'style.md'
    - How to Contribute: 'process.md'
theme: 'readthedocs'
repo_url: https://github.com/dcmi/ldcompindex
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'For crowdsourcing the maintenance and evolution of the LD4PE Linked Data Competency Index'
